name: Publish to NPM

on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # Run when a PR into main is merged, or on direct pushes to main (e.g. squash merges)
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch')
    concurrency:
      group: publish-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          # On PR merge event, check out the actual merge commit; otherwise fallback to current sha
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Decide publish or bump mode
        id: decide
        run: |
          git fetch --tags --force --prune
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          LAST_TAG=$(git tag --list 'v*' | sed 's/^v//' | sort -V | tail -1 || echo "0.0.0")
          LAST_NPM=$(npm view vsix-downloader version 2>/dev/null || echo "0.0.0")
          
          echo "Current version: $CURRENT_VERSION"
          echo "Last tag: $LAST_TAG"
          echo "Last NPM: $LAST_NPM"
          
          # Check if version already exists on NPM
          if npm view vsix-downloader@$CURRENT_VERSION version >/dev/null 2>&1; then
            echo "mode=bump" >> $GITHUB_OUTPUT
            echo "Version $CURRENT_VERSION already exists on NPM. Will prepare bump PR."
          else
            echo "mode=publish" >> $GITHUB_OUTPUT
            echo "Version $CURRENT_VERSION not found on NPM. Will publish."
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests (if any)
        run: npm test --if-present

      - name: Debug workflow state
        run: |
          echo "Workflow mode: ${{ steps.decide.outputs.mode }}"
          echo "Current version: $(node -p "require('./package.json').version")"
          echo "Git SHA: $GITHUB_SHA"
          echo "Event: ${{ github.event_name }}"

      - name: Determine version bump
        id: version
        if: steps.decide.outputs.mode == 'bump'
        run: |
          # Ensure tags are available for accurate diffing
          git fetch --tags --force --prune

          # Get the latest version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          # Get commit messages since last tag OR since last 5 commits if no tags
          if git describe --tags --abbrev=0 >/dev/null 2>&1; then
            SINCE_REF=$(git describe --tags --abbrev=0)
          else
            SINCE_REF=$(git rev-list --max-parents=0 HEAD)
          fi
          COMMITS=$(git log --oneline ${SINCE_REF}..HEAD)

          # Only process if there are new commits
          if [ -z "$COMMITS" ]; then
            echo "bump=none" >> $GITHUB_OUTPUT
            echo "No new commits since last tag"
            exit 0
          fi

          # Determine version bump based on conventional commits
          # Prioritize BREAKING changes first, then features, then fixes/chore/etc
          if echo "$COMMITS" | grep -Eq "^[a-f0-9]+ .*!:|BREAKING CHANGE"; then
              echo "bump=major" >> $GITHUB_OUTPUT
              echo "Breaking changes detected, bumping major version"
          elif echo "$COMMITS" | grep -Eq "^[a-f0-9]+ feat(\(|:| )"; then
              echo "bump=minor" >> $GITHUB_OUTPUT
              echo "New features detected, bumping minor version"
          elif echo "$COMMITS" | grep -Eq "^[a-f0-9]+ (fix|chore|docs|style|refactor|perf|test|ci|build)(\(|:| )"; then
              echo "bump=patch" >> $GITHUB_OUTPUT
              echo "Bug fixes or minor changes detected, bumping patch version"
          else
              echo "bump=none" >> $GITHUB_OUTPUT
              echo "No version bump needed"
          fi

      - name: Bump version
        id: bump
        if: steps.decide.outputs.mode == 'bump' && steps.version.outputs.bump != 'none'
        run: |
          BUMP_TYPE=${{ steps.version.outputs.bump }}
          if [ "$BUMP_TYPE" = "major" ]; then
            npm version major --no-git-tag-version
          elif [ "$BUMP_TYPE" = "minor" ]; then
            npm version minor --no-git-tag-version
          else
            npm version patch --no-git-tag-version
          fi

          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version to $NEW_VERSION"

      - name: Set final version
        if: (steps.decide.outputs.mode == 'bump' && steps.version.outputs.bump != 'none') || (steps.decide.outputs.mode == 'publish')
        id: ensure
        run: |
          FINAL_VERSION=$(node -p "require('./package.json').version")
          echo "final_version=$FINAL_VERSION" >> $GITHUB_OUTPUT
          echo "Using version $FINAL_VERSION for publish"

      - name: Publish to NPM
        if: steps.decide.outputs.mode == 'publish'
        run: |
          echo "Publishing version $(node -p "require('./package.json').version") to NPM..."
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        if: steps.decide.outputs.mode == 'publish'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          TAG_NAME="v${{ steps.ensure.outputs.final_version }}"
          echo "Creating tag $TAG_NAME"
          
          # Create and push tag
          if git tag "$TAG_NAME" $GITHUB_SHA; then
            echo "Tag created successfully"
            git push origin "refs/tags/$TAG_NAME"
            echo "Tag pushed successfully"
          else
            echo "Failed to create tag (may already exist)"
            exit 1
          fi

      - name: Create version bump PR
        if: steps.decide.outputs.mode == 'bump' && steps.version.outputs.bump != 'none'
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          commit-message: "chore: bump version to ${{ steps.ensure.outputs.final_version }}"
          branch: chore/release-v${{ steps.ensure.outputs.final_version }}
          title: "chore: bump version to ${{ steps.ensure.outputs.final_version }}"
          body: |
            This automated PR bumps the package version to `${{ steps.ensure.outputs.final_version }}`
            to reflect the published release. Merging will sync `package.json` with NPM.
          add-paths: |
            package.json

      - name: Create GitHub Release
        if: steps.decide.outputs.mode == 'publish'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.ensure.outputs.final_version }}
          name: Release v${{ steps.ensure.outputs.final_version }}
          body: |
            ## What's Changed

            This release includes the latest changes from the main branch.

            ### Version: ${{ steps.ensure.outputs.final_version }}

            For detailed changes, see the commit history.
          draft: false
          prerelease: false

      - name: Skip publish - no version bump
        if: steps.decide.outputs.mode == 'bump' && steps.version.outputs.bump == 'none'
        run: |
          echo "No version bump needed, skipping publish"
          echo "This usually means no conventional commits were found"

      - name: Skip publish - no-op
        if: steps.decide.outputs.mode == 'bump' && steps.version.outputs.bump == 'none'
        run: echo "No publish actions required"
